"""
Django settings for starlightpath project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# ---------------------------
# Helper parsers for env vars
# ---------------------------
def env_bool(val, default=False):
    if val is None:
        return default
    return str(val).lower() in ("true", "1", "yes", "y", "on")


def env_int(val, default=0):
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def env_list(val, default=None, sep=","):
    if val is None or val == "":
        return default or []
    return [v.strip() for v in str(val).split(sep) if v.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv("SECRET_KEY")
if not _secret_key:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool(os.getenv("DEBUG"), default=False)

ALLOWED_HOSTS = env_list(os.getenv("ALLOWED_HOSTS"), default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # Add third-party apps here
    'rest_framework',                                   # Django Rest Framework
    'drf_spectacular',                                  # DRF Documentation
    'rest_framework_simplejwt.token_blacklist',         # For logout functionality
    'corsheaders',                                      # For handling CORS
]

LOCAL_APPS = [
    # Add local apps here
    "user",
    "application",
    "program",
]

INSTALLED_APPS += THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'starlightpath.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'starlightpath.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# You can configure DB via environment variables. Defaults to SQLite.
# Supported environment variables:
#   DB_ENGINE (default: django.db.backends.sqlite3)
#   DB_NAME (path for sqlite or name for other DBs)
#   DB_USER
#   DB_PASSWORD
#   DB_HOST
#   DB_PORT
DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.sqlite3")
DB_NAME = os.getenv("DB_NAME", str(BASE_DIR / "db.sqlite3"))
DB_USER = os.getenv("DB_USER", "")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")
DB_HOST = os.getenv("DB_HOST", "")
DB_PORT = os.getenv("DB_PORT", "")

if DB_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": DB_NAME,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", str(BASE_DIR / "media")))


AUTH_USER_MODEL = "user.Users"

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env_list(
    os.getenv("CORS_ALLOWED_ORIGINS"),
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
)

# Security cookies — default to True for safety; can be overridden via env for local dev
CSRF_COOKIE_SECURE = env_bool(os.getenv("CSRF_COOKIE_SECURE"), default=not DEBUG)
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = env_bool(os.getenv("SESSION_COOKIE_SECURE"), default=not DEBUG)

# HTTPS / HSTS security headers (read from env for flexibility)
SECURE_SSL_REDIRECT = env_bool(os.getenv("SECURE_SSL_REDIRECT"), default=False)
SECURE_HSTS_SECONDS = env_int(os.getenv("SECURE_HSTS_SECONDS"), default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS"), default=False)
SECURE_HSTS_PRELOAD = env_bool(os.getenv("SECURE_HSTS_PRELOAD"), default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '200/min',
    },
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=env_int(os.getenv("SIMPLE_JWT_ACCESS_TOKEN_HOURS"), 1)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int(os.getenv("SIMPLE_JWT_REFRESH_TOKEN_DAYS"), 7)),
    'ROTATE_REFRESH_TOKENS': env_bool(os.getenv("SIMPLE_JWT_ROTATE_REFRESH_TOKENS"), True),
    'BLACKLIST_AFTER_ROTATION': env_bool(os.getenv("SIMPLE_JWT_BLACKLIST_AFTER_ROTATION"), True),
    'REFRESH_COOKIE_NAME': "refresh_token",
    'REFRESH_COOKIE_PATH': "/api/auth"
}

SPECTACULAR_SETTINGS = {
    'TITLE': os.getenv("SPECTACULAR_TITLE", 'Star Light Path API'),
    'DESCRIPTION': os.getenv("SPECTACULAR_DESCRIPTION", 'API documentation for Star Light Path project'),
    'VERSION': os.getenv("SPECTACULAR_VERSION", '1.0.0'),
    'SERVE_INCLUDE_SCHEMA': env_bool(os.getenv("SPECTACULAR_SERVE_INCLUDE_SCHEMA"), False),
}

# Redis cache (use django-redis)
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": os.getenv("REDIS_PASSWORD", ""),  # if needed
        }
    }
}

# Email (development)
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# For production set SMTP settings instead
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = env_int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = env_bool(os.getenv('EMAIL_USE_TLS'), True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# OTP settings
PASSWORD_RESET_OTP_TTL = env_int(os.getenv("PASSWORD_RESET_OTP_TTL"), 10 * 60)                                          # (Time-To-Live) OTP is valid for 10 minutes
PASSWORD_RESET_OTP_LENGTH = env_int(os.getenv("PASSWORD_RESET_OTP_LENGTH"), 5)                                          # OTP Length
PASSWORD_RESET_MAX_REQUESTS_PER_HOUR = env_int(os.getenv("PASSWORD_RESET_MAX_REQUESTS_PER_HOUR"), 5)                    # Max OTP requests per user per hour
PASSWORD_RESET_MAX_VERIFY_ATTEMPTS = env_int(os.getenv("PASSWORD_RESET_MAX_VERIFY_ATTEMPTS"), 5)                        # User can try verifying OTP only 5 times
PASSWORD_RESET_RESEND_COOLDOWN = env_int(os.getenv("PASSWORD_RESET_RESEND_COOLDOWN"), 60)                               # User must wait 60 seconds before requesting another OTP.
PASSWORD_RESET_VERIFIED_TTL = env_int(os.getenv("PASSWORD_RESET_VERIFIED_TTL"), 10 * 60)                                # After OTP is successfully verified, user has: 10 minutes to reset password
PASSWORD_RESET_OTP_PEPPER = os.getenv("PASSWORD_RESET_OTP_PEPPER", "")                                                  # A secret server-side value added to OTP before hashing.

# Admin notification email URL
ADMIN_LOGIN_URL = os.getenv("ADMIN_LOGIN_URL", "http://localhost:3000/admin/login")

# ── Logging Configuration ──────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'user': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'application': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'program': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
