# Generated by Django 6.0.1 on 2026-01-26 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('APPLY', 'Apply Now'), ('REFER', 'Refer Someone')], default='APPLY', help_text='Apply now or refer someone', max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('living_situation', models.CharField(blank=True, choices=[('HOMELESS', 'Homeless / Shelter / Transitional Housing'), ('HOTEL', 'Hotel / Extended Stay'), ('Staying with Family or Friends', 'With Family'), ('RENTING', 'Renting / Own Home'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('need_housing_when', models.CharField(blank=True, choices=[('IMMEDIATELY', 'Immediately'), ('WITHIN_30_DAYS', 'Within 30 days'), ('ONE_TO_THREE_MONTHS', '1-3 months'), ('THREE_TO_SIX_MONTHS', '3-6 months'), ('MORE_THAN_6_MONTHS', 'More than 6 months'), ('NOT_SURE', 'Not sure yet')], max_length=30, null=True)),
                ('lived_in_shared_before', models.BooleanField(null=True)),
                ('us_veteran', models.BooleanField(null=True)),
                ('transitioning', models.BooleanField(null=True)),
                ('income_sources', models.JSONField(blank=True, default=list)),
                ('income_consistent', models.BooleanField(null=True)),
                ('can_provide_income_docs', models.BooleanField(null=True)),
                ('comfortable_shared', models.BooleanField(null=True)),
                ('asked_to_leave_before', models.BooleanField(null=True)),
                ('has_case_manager', models.BooleanField(null=True)),
                ('case_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('case_manager_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('willing_to_undergo_background_check', models.BooleanField(null=True)),
                ('upcoming_court_dates', models.BooleanField(null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('signature_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('referral_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referral_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
